import { io, type ManagerOptions, type SocketOptions } from 'socket.io-client';

const API_BASE_URL = 'http://localhost:7777';
const ACCESS_TOKEN =
  'eyJraWQiOiJkLTE3MjAxMDgyOTQxMTEiLCJ0eXAiOiJKV1QiLCJ2ZXJzaW9uIjoiNSIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3MjA1ODQyMDksImV4cCI6MTcyMDU4NzgwOSwic3ViIjoiY2VkZjc2YjAtNDZkMi00Zjc0LWI4MTAtMTAxMzNkMGFmNzY4IiwidElkIjoicHVibGljIiwicnN1YiI6ImNlZGY3NmIwLTQ2ZDItNGY3NC1iODEwLTEwMTMzZDBhZjc2OCIsInNlc3Npb25IYW5kbGUiOiI5MWU2YWE4Yy1hOWEyLTQ4NmUtYmM5YS00NTFjNDkyM2M1MzgiLCJyZWZyZXNoVG9rZW5IYXNoMSI6ImI1NzgwYzc3OWU4N2RkZDc4Y2IzNGFjMWM5NjQ2YmMxYjM2M2Y1ZmY2YTZkMzFmYmMxYmYwMTVmZTM0ZTlmMDEiLCJwYXJlbnRSZWZyZXNoVG9rZW5IYXNoMSI6bnVsbCwiYW50aUNzcmZUb2tlbiI6bnVsbCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0MDAxL2F1dGgiLCJzdC1yb2xlIjp7InYiOltdLCJ0IjoxNzIwNTg0MjA5NjcyfSwic3QtcGVybSI6eyJ2IjpbXSwidCI6MTcyMDU4NDIwOTY5MX0sImN1c3RvbUNsYWltIjp7InN1cHBsaWVyIjp7fSwiY29tcGFueSI6eyJjcmVhdGVkQXQiOiIyMDI0LTA0LTI1VDEzOjU3OjQ1LjIwM1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTA0LTI1VDEzOjU3OjQ1LjIwM1oiLCJkZWxldGVkQXQiOm51bGwsInN0YXR1cyI6MSwiY29tcGFueUlkIjoxNjYsImNvbXBhbnlUeXBlIjoiY3VzdG9tZXIiLCJjb21wYW55TGluayI6Mn0sInVzZXIiOnsiY3JlYXRlZEF0IjoiMjAyNC0wNS0zMVQxMTowNToyMi4xMjJaIiwidXBkYXRlZEF0IjoiMjAyNC0wNS0zMVQxMTowNToyMi4xMjJaIiwiZGVsZXRlZEF0IjpudWxsLCJzdGF0dXMiOjEsInVzZXJJZCI6NjYsInN1cGVydG9rZW5JZCI6ImNlZGY3NmIwLTQ2ZDItNGY3NC1iODEwLTEwMTMzZDBhZjc2OCIsImVtYWlsIjoiZGVtby51c2VyMkB0ZXN0LmlvIiwicHJvZmlsZVBpY3R1cmUiOm51bGwsImZpcnN0TmFtZSI6ImRlbW8iLCJsYXN0TmFtZSI6InVzZXIyIiwicGhvbmVOdW1iZXIiOiIiLCJ0aXRsZSI6bnVsbCwiY29udGFjdFR5cGUiOiJjdXN0b21lciIsImRlcGFydG1lbnQiOm51bGwsImlzUHJpbWFyeUNvbnRhY3QiOnRydWUsImlzUG9ydGFsVXNlciI6dHJ1ZSwicm9sZXMiOltdLCJjdXN0b21lciI6W10sInN1cHBsaWVyIjpbXSwiY29tcGFueUlkIjoxNjYsInBlcm1pc3Npb25zIjpbXX0sImN1c3RvbWVyIjp7ImNyZWF0ZWRBdCI6IjIwMjQtMDMtMDRUMTQ6MjY6MzYuMDE2WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMThUMTA6NTc6MjUuOTY0WiIsImRlbGV0ZWRBdCI6bnVsbCwic3RhdHVzIjoxLCJjdXN0b21lcklkIjoyLCJuZXRzdWl0ZUlkIjoiMTE5IiwiY29tcGFueU5hbWUiOiJTd2l0Y2gsIEluYy4iLCJkZWZhdWx0QWRkcmVzcyI6IlN3aXRjaCwgSW5jLlxuUE8gQm94IDQwMDg1MFxuTGFzIFZlZ2FzIE5ldmFkYSA4OTE0MFxuVW5pdGVkIFN0YXRlcyIsInBob25lTnVtYmVyIjoiNzAyNDQ0NDAwMCIsImxhc3RTeW5jRGF0ZSI6IjIwMjQtMDYtMThUMTA6NTc6MjUuOTU5WiJ9LCJ0eXBlIjoiY3VzdG9tZXIiLCJlbWFpbCI6ImRlbW8udXNlcjJAdGVzdC5pbyJ9fQ.atW0UB4QPuhfc4xKddfVQMDqqQxlx1T_YI-OmZmhn_lXQYGz0sP6Ykqmw1jLMthDoUpRAEBZCBRlbDU0jvWjJkFdJfGTe6xvblZKzbv9gYdGeHZRuAEysgoXsvzG7V-to6zPs6bQA5d9_2MdBSs6T-9YKDKFUxbS-QXgADjK9S_yHFDA1B-U5th32rzjBzRtutt1yWPivHnR8bGsP_7OiBXGhWYnbkmLXmb3RZ5Gptw_fWqXkEIihu8JKiEezcBmF9ZDyKbce7zI3JuZQHQ9zVwA9m8S3aM4taK1QWOM4uzYzsnd2m4JiDYY8rLCSob4x9ePsoiD_skH1CJ4OleioQ';

// Connect to the server
const socket = io(API_BASE_URL, {
  auth: {
    token: ACCESS_TOKEN,
  },
});

console.log('LISTENING');
// Event listener for successful connection
socket.on('connect', () => {
  console.log('Connected to server');

  // Send a test message to the server
  socket.emit('testMessage', 'Hello, server!');
});

// Event listener for receiving messages from the server
socket.on('serverMessage', (data) => {
  console.log('Received message from server:', data);
});

// Event listener for disconnection
socket.on('disconnect', () => {
  console.log('Disconnected from server');
});

// Error event listener
socket.on('error', (error) => {
  console.error('Socket error:', error);
});
